CREATE TABLE PLM_FILE
(
  ID        BIGINT PRIMARY KEY,
  UID       VARCHAR(255) NOT NULL,
  FILENAME  VARCHAR(255) NULL,
  FILE_TYPE VARCHAR(255) NOT NULL,
);

/* If saving on database */

CREATE TABLE PLM_FILE_DATA
(
  ID_FILE BIGINT,
  DATA    VARBINARY(MAX) NOT NULL,
  CONSTRAINT PLM_FILE_FK FOREIGN KEY (ID_FILE)
  REFERENCES PLM_FILE(ID)
);

/* If saving on disk */

CREATE TABLE PLM_FILE_DISK
(
  ID_FILE BIGINT,
  PATH    VARCHAR(255) NOT NULL,
  CONSTRAINT PLM_FILE_FK FOREIGN KEY (ID_FILE)
  REFERENCES PLM_FILE(ID)
);

GO
