file.storage.gcp.bucket-name = "gcp-bucket-name"
file.storage.gcp.project-id = "project-id"
file.storage.gcp.bucket-base-path = "bucket-base-path"
file.storage.gcp.credentials-path = "/path-to/credential-file.json"
